import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../providers/ReduxProvider";
import QueryProvider from "../providers/QueryProvider";
import SyncUser from "@/components/ui/SyncUser";
import { ConvexClientProvider } from "@/providers/ConvexProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClientProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <QueryProvider>
            <ReduxProvider>
              <SyncUser />
              <EdgeStoreProvider>
                <Toaster position="bottom-center" />
                {children}</EdgeStoreProvider>
            </ReduxProvider>
          </QueryProvider>
        </body>
      </html>
    </ConvexClientProvider>
  );
}
